### ISSUE TITLE
Example code mistake

### ISSUE THREAD

**Issue by simonepernice** [ozhantr/DigitLedDisplay#5]
The example code has a typo:

/* Arduino Pin to Display Pin
   7 to DIN,
   6 to CS,
   5 to CLK */
DigitLedDisplay ld = DigitLedDisplay(7, 5, 6);

should be:

DigitLedDisplay ld = DigitLedDisplay(7, 6, 5);

**Comment by per1234** [comment]
There's a pull request to fix this issue: https://github.com/ozhantr/DigitLedDisplay/pull/4

**Comment by tobiasbp** [comment]
I just spent hours on this (Found out using oscilloscope).
