### ISSUE TITLE
avr/pgmspace.h: No such file or directory on ESP8266

### ISSUE THREAD

**Issue by dhessmann** [ozhantr/DigitLedDisplay#8]
Hi,

when using an esp8266 you get an "avr/pgmspace.h: No such file or directory".
Could you replace 
```
#include <avr\pgmspace.h>
```
with
```
#if (defined(__AVR__))
#include <avr\pgmspace.h>
#else
#include <pgmspace.h>
#endif
```
like mentioned here: `https://github.com/SodaqMoja/Sodaq_DS3231/issues/5`?

Thanks.

**Comment by ozhantr** [comment]
Thx @dhessmann. I have fixed the path.
